// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmsCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` // 手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeRequest) Reset() {
	*x = SendSmsCodeRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeRequest) ProtoMessage() {}

func (x *SendSmsCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeRequest.ProtoReflect.Descriptor instead.
func (*SendSmsCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsCodeRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type SendSmsCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsCodeResponse) Reset() {
	*x = SendSmsCodeResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsCodeResponse) ProtoMessage() {}

func (x *SendSmsCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsCodeResponse.ProtoReflect.Descriptor instead.
func (*SendSmsCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSmsCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PhoneLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` // 手机号
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`     // 验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginRequest) Reset() {
	*x = PhoneLoginRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginRequest) ProtoMessage() {}

func (x *PhoneLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginRequest.ProtoReflect.Descriptor instead.
func (*PhoneLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *PhoneLoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *PhoneLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PhoneLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // id
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginResponse) Reset() {
	*x = PhoneLoginResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginResponse) ProtoMessage() {}

func (x *PhoneLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginResponse.ProtoReflect.Descriptor instead.
func (*PhoneLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *PhoneLoginResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PhoneLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VideoWorksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Desc           string                 `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	MusicId        uint64                 `protobuf:"varint,3,opt,name=MusicId,proto3" json:"MusicId,omitempty"`
	WorkType       string                 `protobuf:"bytes,4,opt,name=WorkType,proto3" json:"WorkType,omitempty"`
	CheckStatus    string                 `protobuf:"bytes,5,opt,name=CheckStatus,proto3" json:"CheckStatus,omitempty"`
	CheckUser      uint64                 `protobuf:"varint,6,opt,name=CheckUser,proto3" json:"CheckUser,omitempty"`
	IpAddress      string                 `protobuf:"bytes,7,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
	WorkPermission string                 `protobuf:"bytes,8,opt,name=WorkPermission,proto3" json:"WorkPermission,omitempty"`
	LikeCount      uint64                 `protobuf:"varint,9,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	CommentCount   uint64                 `protobuf:"varint,10,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`
	ShareCount     uint64                 `protobuf:"varint,11,opt,name=ShareCount,proto3" json:"ShareCount,omitempty"`
	CollectCount   uint64                 `protobuf:"varint,12,opt,name=CollectCount,proto3" json:"CollectCount,omitempty"`
	BrowseCount    uint64                 `protobuf:"varint,13,opt,name=BrowseCount,proto3" json:"BrowseCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoWorksRequest) Reset() {
	*x = VideoWorksRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoWorksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoWorksRequest) ProtoMessage() {}

func (x *VideoWorksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoWorksRequest.ProtoReflect.Descriptor instead.
func (*VideoWorksRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *VideoWorksRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoWorksRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *VideoWorksRequest) GetMusicId() uint64 {
	if x != nil {
		return x.MusicId
	}
	return 0
}

func (x *VideoWorksRequest) GetWorkType() string {
	if x != nil {
		return x.WorkType
	}
	return ""
}

func (x *VideoWorksRequest) GetCheckStatus() string {
	if x != nil {
		return x.CheckStatus
	}
	return ""
}

func (x *VideoWorksRequest) GetCheckUser() uint64 {
	if x != nil {
		return x.CheckUser
	}
	return 0
}

func (x *VideoWorksRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *VideoWorksRequest) GetWorkPermission() string {
	if x != nil {
		return x.WorkPermission
	}
	return ""
}

func (x *VideoWorksRequest) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *VideoWorksRequest) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *VideoWorksRequest) GetShareCount() uint64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *VideoWorksRequest) GetCollectCount() uint64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *VideoWorksRequest) GetBrowseCount() uint64 {
	if x != nil {
		return x.BrowseCount
	}
	return 0
}

type VideoWorksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // id
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoWorksResponse) Reset() {
	*x = VideoWorksResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoWorksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoWorksResponse) ProtoMessage() {}

func (x *VideoWorksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoWorksResponse.ProtoReflect.Descriptor instead.
func (*VideoWorksResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *VideoWorksResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VideoWorksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VideoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint64                 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoListRequest) Reset() {
	*x = VideoListRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListRequest) ProtoMessage() {}

func (x *VideoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListRequest.ProtoReflect.Descriptor instead.
func (*VideoListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *VideoListRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *VideoListRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VideoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListWorks           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoListResponse) Reset() {
	*x = VideoListResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListResponse) ProtoMessage() {}

func (x *VideoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListResponse.ProtoReflect.Descriptor instead.
func (*VideoListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *VideoListResponse) GetList() []*ListWorks {
	if x != nil {
		return x.List
	}
	return nil
}

type ListWorks struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Desc           string                 `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	MusicId        uint64                 `protobuf:"varint,3,opt,name=MusicId,proto3" json:"MusicId,omitempty"`
	WorkType       string                 `protobuf:"bytes,4,opt,name=WorkType,proto3" json:"WorkType,omitempty"`
	CheckStatus    string                 `protobuf:"bytes,5,opt,name=CheckStatus,proto3" json:"CheckStatus,omitempty"`
	CheckUser      uint64                 `protobuf:"varint,6,opt,name=CheckUser,proto3" json:"CheckUser,omitempty"`
	IpAddress      string                 `protobuf:"bytes,7,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
	WorkPermission string                 `protobuf:"bytes,8,opt,name=WorkPermission,proto3" json:"WorkPermission,omitempty"`
	LikeCount      uint64                 `protobuf:"varint,9,opt,name=LikeCount,proto3" json:"LikeCount,omitempty"`
	CommentCount   uint64                 `protobuf:"varint,10,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`
	ShareCount     uint64                 `protobuf:"varint,11,opt,name=ShareCount,proto3" json:"ShareCount,omitempty"`
	CollectCount   uint64                 `protobuf:"varint,12,opt,name=CollectCount,proto3" json:"CollectCount,omitempty"`
	BrowseCount    uint64                 `protobuf:"varint,13,opt,name=BrowseCount,proto3" json:"BrowseCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListWorks) Reset() {
	*x = ListWorks{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorks) ProtoMessage() {}

func (x *ListWorks) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorks.ProtoReflect.Descriptor instead.
func (*ListWorks) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorks) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListWorks) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ListWorks) GetMusicId() uint64 {
	if x != nil {
		return x.MusicId
	}
	return 0
}

func (x *ListWorks) GetWorkType() string {
	if x != nil {
		return x.WorkType
	}
	return ""
}

func (x *ListWorks) GetCheckStatus() string {
	if x != nil {
		return x.CheckStatus
	}
	return ""
}

func (x *ListWorks) GetCheckUser() uint64 {
	if x != nil {
		return x.CheckUser
	}
	return 0
}

func (x *ListWorks) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ListWorks) GetWorkPermission() string {
	if x != nil {
		return x.WorkPermission
	}
	return ""
}

func (x *ListWorks) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ListWorks) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *ListWorks) GetShareCount() uint64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *ListWorks) GetCollectCount() uint64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *ListWorks) GetBrowseCount() uint64 {
	if x != nil {
		return x.BrowseCount
	}
	return 0
}

// 评论更新
type UpdateVideoWorkCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	WorkId        uint64                 `protobuf:"varint,2,opt,name=WorkId,proto3" json:"WorkId,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	Tag           uint64                 `protobuf:"varint,5,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Pid           uint64                 `protobuf:"varint,6,opt,name=Pid,proto3" json:"Pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoWorkCommentRequest) Reset() {
	*x = UpdateVideoWorkCommentRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoWorkCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoWorkCommentRequest) ProtoMessage() {}

func (x *UpdateVideoWorkCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoWorkCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoWorkCommentRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVideoWorkCommentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVideoWorkCommentRequest) GetWorkId() uint64 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *UpdateVideoWorkCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateVideoWorkCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateVideoWorkCommentRequest) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *UpdateVideoWorkCommentRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type UpdateVideoWorkCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoWorkCommentResponse) Reset() {
	*x = UpdateVideoWorkCommentResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoWorkCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoWorkCommentResponse) ProtoMessage() {}

func (x *UpdateVideoWorkCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoWorkCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoWorkCommentResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVideoWorkCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVideoWorkCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 评论删除
type DeleteVideoWorkCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoWorkCommentRequest) Reset() {
	*x = DeleteVideoWorkCommentRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoWorkCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoWorkCommentRequest) ProtoMessage() {}

func (x *DeleteVideoWorkCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoWorkCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoWorkCommentRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVideoWorkCommentRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVideoWorkCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoWorkCommentResponse) Reset() {
	*x = DeleteVideoWorkCommentResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoWorkCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoWorkCommentResponse) ProtoMessage() {}

func (x *DeleteVideoWorkCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoWorkCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoWorkCommentResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVideoWorkCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVideoWorkCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 评论展示
type ListVideoWorkCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoWorkCommentRequest) Reset() {
	*x = ListVideoWorkCommentRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoWorkCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoWorkCommentRequest) ProtoMessage() {}

func (x *ListVideoWorkCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoWorkCommentRequest.ProtoReflect.Descriptor instead.
func (*ListVideoWorkCommentRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

type ListVideoWorkCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListComment         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideoWorkCommentResponse) Reset() {
	*x = ListVideoWorkCommentResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideoWorkCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideoWorkCommentResponse) ProtoMessage() {}

func (x *ListVideoWorkCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideoWorkCommentResponse.ProtoReflect.Descriptor instead.
func (*ListVideoWorkCommentResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *ListVideoWorkCommentResponse) GetList() []*ListComment {
	if x != nil {
		return x.List
	}
	return nil
}

type ListComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        uint64                 `protobuf:"varint,1,opt,name=WorkId,proto3" json:"WorkId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Tag           uint64                 `protobuf:"varint,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Pid           uint64                 `protobuf:"varint,5,opt,name=Pid,proto3" json:"Pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListComment) Reset() {
	*x = ListComment{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComment) ProtoMessage() {}

func (x *ListComment) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComment.ProtoReflect.Descriptor instead.
func (*ListComment) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListComment) GetWorkId() uint64 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *ListComment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ListComment) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *ListComment) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// 评论发布
type AddVideoWorkCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        uint64                 `protobuf:"varint,1,opt,name=WorkId,proto3" json:"WorkId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	Tag           uint64                 `protobuf:"varint,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Pid           uint64                 `protobuf:"varint,5,opt,name=Pid,proto3" json:"Pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideoWorkCommentRequest) Reset() {
	*x = AddVideoWorkCommentRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideoWorkCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideoWorkCommentRequest) ProtoMessage() {}

func (x *AddVideoWorkCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideoWorkCommentRequest.ProtoReflect.Descriptor instead.
func (*AddVideoWorkCommentRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *AddVideoWorkCommentRequest) GetWorkId() uint64 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *AddVideoWorkCommentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddVideoWorkCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddVideoWorkCommentRequest) GetTag() uint64 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *AddVideoWorkCommentRequest) GetPid() uint64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type AddVideoWorkCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVideoWorkCommentResponse) Reset() {
	*x = AddVideoWorkCommentResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVideoWorkCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideoWorkCommentResponse) ProtoMessage() {}

func (x *AddVideoWorkCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideoWorkCommentResponse.ProtoReflect.Descriptor instead.
func (*AddVideoWorkCommentResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *AddVideoWorkCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddVideoWorkCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 审核
type AnthorCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CheckStatus   string                 `protobuf:"bytes,2,opt,name=CheckStatus,proto3" json:"CheckStatus,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=Remark,proto3" json:"Remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthorCheckRequest) Reset() {
	*x = AnthorCheckRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthorCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthorCheckRequest) ProtoMessage() {}

func (x *AnthorCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthorCheckRequest.ProtoReflect.Descriptor instead.
func (*AnthorCheckRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *AnthorCheckRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AnthorCheckRequest) GetCheckStatus() string {
	if x != nil {
		return x.CheckStatus
	}
	return ""
}

func (x *AnthorCheckRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type AnthorCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthorCheckResponse) Reset() {
	*x = AnthorCheckResponse{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthorCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthorCheckResponse) ProtoMessage() {}

func (x *AnthorCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthorCheckResponse.ProtoReflect.Descriptor instead.
func (*AnthorCheckResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *AnthorCheckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnthorCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\",\n" +
	"\x12SendSmsCodeRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"I\n" +
	"\x13SendSmsCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x11PhoneLoginRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\">\n" +
	"\x12PhoneLoginResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x03\n" +
	"\x11VideoWorksRequest\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x12\n" +
	"\x04Desc\x18\x02 \x01(\tR\x04Desc\x12\x18\n" +
	"\aMusicId\x18\x03 \x01(\x04R\aMusicId\x12\x1a\n" +
	"\bWorkType\x18\x04 \x01(\tR\bWorkType\x12 \n" +
	"\vCheckStatus\x18\x05 \x01(\tR\vCheckStatus\x12\x1c\n" +
	"\tCheckUser\x18\x06 \x01(\x04R\tCheckUser\x12\x1c\n" +
	"\tIpAddress\x18\a \x01(\tR\tIpAddress\x12&\n" +
	"\x0eWorkPermission\x18\b \x01(\tR\x0eWorkPermission\x12\x1c\n" +
	"\tLikeCount\x18\t \x01(\x04R\tLikeCount\x12\"\n" +
	"\fCommentCount\x18\n" +
	" \x01(\x04R\fCommentCount\x12\x1e\n" +
	"\n" +
	"ShareCount\x18\v \x01(\x04R\n" +
	"ShareCount\x12\"\n" +
	"\fCollectCount\x18\f \x01(\x04R\fCollectCount\x12 \n" +
	"\vBrowseCount\x18\r \x01(\x04R\vBrowseCount\">\n" +
	"\x12VideoWorksResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x10VideoListRequest\x12\x12\n" +
	"\x04Page\x18\x01 \x01(\x04R\x04Page\x12\x12\n" +
	"\x04Size\x18\x02 \x01(\x04R\x04Size\"9\n" +
	"\x11VideoListResponse\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.proto.ListWorksR\x04list\"\x99\x03\n" +
	"\tListWorks\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x12\n" +
	"\x04Desc\x18\x02 \x01(\tR\x04Desc\x12\x18\n" +
	"\aMusicId\x18\x03 \x01(\x04R\aMusicId\x12\x1a\n" +
	"\bWorkType\x18\x04 \x01(\tR\bWorkType\x12 \n" +
	"\vCheckStatus\x18\x05 \x01(\tR\vCheckStatus\x12\x1c\n" +
	"\tCheckUser\x18\x06 \x01(\x04R\tCheckUser\x12\x1c\n" +
	"\tIpAddress\x18\a \x01(\tR\tIpAddress\x12&\n" +
	"\x0eWorkPermission\x18\b \x01(\tR\x0eWorkPermission\x12\x1c\n" +
	"\tLikeCount\x18\t \x01(\x04R\tLikeCount\x12\"\n" +
	"\fCommentCount\x18\n" +
	" \x01(\x04R\fCommentCount\x12\x1e\n" +
	"\n" +
	"ShareCount\x18\v \x01(\x04R\n" +
	"ShareCount\x12\"\n" +
	"\fCollectCount\x18\f \x01(\x04R\fCollectCount\x12 \n" +
	"\vBrowseCount\x18\r \x01(\x04R\vBrowseCount\"\x9d\x01\n" +
	"\x1dUpdateVideoWorkCommentRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x16\n" +
	"\x06WorkId\x18\x02 \x01(\x04R\x06WorkId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\x12\x10\n" +
	"\x03Tag\x18\x05 \x01(\x04R\x03Tag\x12\x10\n" +
	"\x03Pid\x18\x06 \x01(\x04R\x03Pid\"T\n" +
	"\x1eUpdateVideoWorkCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x1dDeleteVideoWorkCommentRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\"T\n" +
	"\x1eDeleteVideoWorkCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1d\n" +
	"\x1bListVideoWorkCommentRequest\"F\n" +
	"\x1cListVideoWorkCommentResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.proto.ListCommentR\x04list\"{\n" +
	"\vListComment\x12\x16\n" +
	"\x06WorkId\x18\x01 \x01(\x04R\x06WorkId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12\x10\n" +
	"\x03Tag\x18\x04 \x01(\x04R\x03Tag\x12\x10\n" +
	"\x03Pid\x18\x05 \x01(\x04R\x03Pid\"\x8a\x01\n" +
	"\x1aAddVideoWorkCommentRequest\x12\x16\n" +
	"\x06WorkId\x18\x01 \x01(\x04R\x06WorkId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x04R\x06UserId\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12\x10\n" +
	"\x03Tag\x18\x04 \x01(\x04R\x03Tag\x12\x10\n" +
	"\x03Pid\x18\x05 \x01(\x04R\x03Pid\"Q\n" +
	"\x1bAddVideoWorkCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\x12AnthorCheckRequest\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12 \n" +
	"\vCheckStatus\x18\x02 \x01(\tR\vCheckStatus\x12\x16\n" +
	"\x06Remark\x18\x03 \x01(\tR\x06Remark\"I\n" +
	"\x13AnthorCheckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe5\x05\n" +
	"\x04User\x12D\n" +
	"\vSendSmsCode\x12\x19.proto.SendSmsCodeRequest\x1a\x1a.proto.SendSmsCodeResponse\x12A\n" +
	"\n" +
	"PhoneLogin\x12\x18.proto.PhoneLoginRequest\x1a\x19.proto.PhoneLoginResponse\x12A\n" +
	"\n" +
	"VideoWorks\x12\x18.proto.VideoWorksRequest\x1a\x19.proto.VideoWorksResponse\x12>\n" +
	"\tVideoList\x12\x17.proto.VideoListRequest\x1a\x18.proto.VideoListResponse\x12e\n" +
	"\x16UpdateVideoWorkComment\x12$.proto.UpdateVideoWorkCommentRequest\x1a%.proto.UpdateVideoWorkCommentResponse\x12e\n" +
	"\x16DeleteVideoWorkComment\x12$.proto.DeleteVideoWorkCommentRequest\x1a%.proto.DeleteVideoWorkCommentResponse\x12_\n" +
	"\x14ListVideoWorkComment\x12\".proto.ListVideoWorkCommentRequest\x1a#.proto.ListVideoWorkCommentResponse\x12\\\n" +
	"\x13AddVideoWorkComment\x12!.proto.AddVideoWorkCommentRequest\x1a\".proto.AddVideoWorkCommentResponse\x12D\n" +
	"\vAnthorCheck\x12\x19.proto.AnthorCheckRequest\x1a\x1a.proto.AnthorCheckResponseB\x03Z\x01/b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_proto_goTypes = []any{
	(*SendSmsCodeRequest)(nil),             // 0: proto.SendSmsCodeRequest
	(*SendSmsCodeResponse)(nil),            // 1: proto.SendSmsCodeResponse
	(*PhoneLoginRequest)(nil),              // 2: proto.PhoneLoginRequest
	(*PhoneLoginResponse)(nil),             // 3: proto.PhoneLoginResponse
	(*VideoWorksRequest)(nil),              // 4: proto.VideoWorksRequest
	(*VideoWorksResponse)(nil),             // 5: proto.VideoWorksResponse
	(*VideoListRequest)(nil),               // 6: proto.VideoListRequest
	(*VideoListResponse)(nil),              // 7: proto.VideoListResponse
	(*ListWorks)(nil),                      // 8: proto.ListWorks
	(*UpdateVideoWorkCommentRequest)(nil),  // 9: proto.UpdateVideoWorkCommentRequest
	(*UpdateVideoWorkCommentResponse)(nil), // 10: proto.UpdateVideoWorkCommentResponse
	(*DeleteVideoWorkCommentRequest)(nil),  // 11: proto.DeleteVideoWorkCommentRequest
	(*DeleteVideoWorkCommentResponse)(nil), // 12: proto.DeleteVideoWorkCommentResponse
	(*ListVideoWorkCommentRequest)(nil),    // 13: proto.ListVideoWorkCommentRequest
	(*ListVideoWorkCommentResponse)(nil),   // 14: proto.ListVideoWorkCommentResponse
	(*ListComment)(nil),                    // 15: proto.ListComment
	(*AddVideoWorkCommentRequest)(nil),     // 16: proto.AddVideoWorkCommentRequest
	(*AddVideoWorkCommentResponse)(nil),    // 17: proto.AddVideoWorkCommentResponse
	(*AnthorCheckRequest)(nil),             // 18: proto.AnthorCheckRequest
	(*AnthorCheckResponse)(nil),            // 19: proto.AnthorCheckResponse
}
var file_user_proto_depIdxs = []int32{
	8,  // 0: proto.VideoListResponse.list:type_name -> proto.ListWorks
	15, // 1: proto.ListVideoWorkCommentResponse.list:type_name -> proto.ListComment
	0,  // 2: proto.User.SendSmsCode:input_type -> proto.SendSmsCodeRequest
	2,  // 3: proto.User.PhoneLogin:input_type -> proto.PhoneLoginRequest
	4,  // 4: proto.User.VideoWorks:input_type -> proto.VideoWorksRequest
	6,  // 5: proto.User.VideoList:input_type -> proto.VideoListRequest
	9,  // 6: proto.User.UpdateVideoWorkComment:input_type -> proto.UpdateVideoWorkCommentRequest
	11, // 7: proto.User.DeleteVideoWorkComment:input_type -> proto.DeleteVideoWorkCommentRequest
	13, // 8: proto.User.ListVideoWorkComment:input_type -> proto.ListVideoWorkCommentRequest
	16, // 9: proto.User.AddVideoWorkComment:input_type -> proto.AddVideoWorkCommentRequest
	18, // 10: proto.User.AnthorCheck:input_type -> proto.AnthorCheckRequest
	1,  // 11: proto.User.SendSmsCode:output_type -> proto.SendSmsCodeResponse
	3,  // 12: proto.User.PhoneLogin:output_type -> proto.PhoneLoginResponse
	5,  // 13: proto.User.VideoWorks:output_type -> proto.VideoWorksResponse
	7,  // 14: proto.User.VideoList:output_type -> proto.VideoListResponse
	10, // 15: proto.User.UpdateVideoWorkComment:output_type -> proto.UpdateVideoWorkCommentResponse
	12, // 16: proto.User.DeleteVideoWorkComment:output_type -> proto.DeleteVideoWorkCommentResponse
	14, // 17: proto.User.ListVideoWorkComment:output_type -> proto.ListVideoWorkCommentResponse
	17, // 18: proto.User.AddVideoWorkComment:output_type -> proto.AddVideoWorkCommentResponse
	19, // 19: proto.User.AnthorCheck:output_type -> proto.AnthorCheckResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
